- go.mod
- go.sum
- internal/csi/driver/camanager.go
- internal/csi/driver/camanager_test.go
- internal/csi/driver/driver.go
- internal/csi/driver/driver_test.go
This PR ensures that the driver writes certificate key pairs which are compatible with the [go-spiffe x509svid.Parse](https://github.com/spiffe/go-spiffe/blob/31de176038793c17cf7e77f23e61401160c7d6c9/v2/svid/x509svid/svid.go#L50) library function.
To do this, the private key marshalling has been changed from `MarshalECPrivateKey` -> `MarshalPKCS8PrivateKey` and PEM header `EC PRIVATE KEY` -> `PRIVATE KEY`.
In order to test this, the `camanager` driver component has been split out into its own struct. This was required since the `camanager` absolutely needs a [`filesystem` storage](https://github.com/cert-manager/csi-lib/blob/main/storage/filesystem.go) (in order to read files back), however we need to use the store `Interface` for the `writeKeypair` func so `InMemory` can be used for …
> Make CSI driver spiffe writeFiles compatable with go-spiffe `x509svid.Parse`

- Makefile
- deploy/charts/csi-driver-spiffe/README.md
- go.mod
- go.sum
- hack/tools/tools.go
- hack/update-helm-docs.sh
- hack/verify-helm-docs.sh
/assign @munnerz 
This PR adds a scripts, run at make lint, which verifies that the helm chart README.md file is kept up to date.
An update script is also added which will update the helm chart README.md.
> Adds verify-helm-docs.sh and update-helm-docs.sh scripts. Verify helm-docs during lint

- README.md
Will stealth merge using a manual `lgtm` label
> Update logo to smaller version, fix broken HTML

- deploy/charts/csi-driver-spiffe/Chart.yaml
- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
See https://github.com/cert-manager/csi-driver/pull/110
Updates helm chart version to v0.2.1, ready for release.
>  Remove life cycle hook from Daemonset

- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/values.yaml
k8s.gcr.io registry is deprecated and to be shut down https://groups.google.com/a/kubernetes.io/g/dev/c/DYZYNQ_A6_c
This PR changes the registry of upstream CSI driver sidecar images to the new registry.k8s.io and also bumps to the latest minor versions of those images.
> Ensures that CSI driver sidecar images are latest from registry.k8s.io

- Dockerfile.approver
- Dockerfile.driver
- Makefile
- go.mod
- go.sum
Bump to go 1.19, bump dep versions and fix CVEs
Fixes https://github.com/advisories/GHSA-xrjj-mj9h-534m and CVE-2022-41723
Also updates distroless base image for new tzdata
> Bump go, deps, base images

- internal/approver/evaluator/evaluator.go
- internal/approver/evaluator/evaluator_test.go
- internal/csi/driver/driver_test.go
- internal/csi/driver/util.go
It seems the original choice to use P-521 [may have been a mistake](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1676473986055109), and in any case there's no real cryptographic justification for using it here over P-256 which will be faster and more widely supported.
Specifically, we've heard that envoy struggles with P-521 so switching will help with that use case.
This also removes the approver check for the curve. That check was incorrect (**checking the bit size of the underlying field doesn't confirm that the curve is P-521**) and was not in any case a worthwhile thing to confirm since we shouldn't really care what key is used.
> Change to use p256 instead of p521

- Makefile
- deploy/charts/csi-driver-spiffe/Chart.yaml
- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/templates/NOTES.txt
- deploy/charts/csi-driver-spiffe/values.yaml
This prepares for a release of 0.3.0, removes old info and improves the Helm chart.
This also adds a "image-push" target to help with releases. It's not ideal, but it works and doesn't leave us releasing from a dirty checkout.
> Bump versions, fix old info

- Makefile
As implemented, this will create a chart with version `0.3.0` instead of `v0.3.0` which will cause the Jetstack-internal charts repo to interpret the chart as invalid and in any case is a deviation from past charts where the versions were prefixed with `v`.
This change will apply to the release in v0.3.0 since it's minor and doesn't affect running code but is required for the release.
The release won't be retagged because it doesn't seem worth it.
> Change release version to use a v, fixes generation of chart

- hack/update-helm-docs.sh
- hack/verify-boilerplate.sh
- hack/verify-helm-docs.sh
> Use `/usr/bin/env` instead of `/bin/bash` in hack scripts

- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
This was missing in the daemonset but present in the deployment with the confusing effect that the csidriver was listed when listing the csidrivers but reported as missing, when being useD
> Add missing --csi-driver-name option to daemonset

- Makefile
- go.mod
- go.sum
- hack/verify-helm-docs.sh
#33 but smaller, just fixes the problem we have today without trying to improve anything else
> Bump helm docs

- deploy/charts/csi-driver-spiffe/templates/csidriver.yaml
- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
- deploy/charts/csi-driver-spiffe/templates/deployment.yaml
- deploy/charts/csi-driver-spiffe/templates/metrics-service.yaml
- deploy/charts/csi-driver-spiffe/templates/role.yaml
- deploy/charts/csi-driver-spiffe/templates/rolebinding.yaml
- deploy/charts/csi-driver-spiffe/templates/serviceaccount.yaml
- remove deprecated `storage.k8s.io/v1beta1`
- add namespace values that make sure namespace is included when running `helm template`
- use dynamic `$(POD_NAMESPACE)` instead of static templated `{{ .Release.Namespace }}` value (should resolve to same value)
> Helm chart improvements

- Makefile
This prevents confusion on an initial checkout
> Ensure bindir exists before running certain commands

- Dockerfile.driver
- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/values.yaml
See [slack](https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1700568998836669)
> Tweak golang base image + update dependent container images

- internal/csi/app/app.go
- internal/csi/driver/camanager.go
- internal/csi/driver/driver.go
- internal/version/version.go
Prints the version info on startup and passes the version string to csi-lib.
> Add version info to binary at compile time

- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/templates/_helpers.tpl
- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
- deploy/charts/csi-driver-spiffe/templates/deployment.yaml
- deploy/charts/csi-driver-spiffe/values.linter.exceptions
- deploy/charts/csi-driver-spiffe/values.schema.json
- deploy/charts/csi-driver-spiffe/values.yaml
- make/00_mod.mk
Enabling these two features that were added in the Helm module:
https://github.com/cert-manager/csi-driver-spiffe/blob/cd2a498532c20cc4813012f16c4f36fbe91d2f76/make/00_mod.mk#L52-L53
> Enable helm-tool linter and schema generator

- internal/approver/controller/controller.go
```console
$ go doc os Exit
package os // import os
func Exit(code int)
Exit causes the current program to exit with the given status code.
Conventionally, code zero indicates success, non-zero an error. The program
terminates immediately; deferred functions are not run.
For portability, the status code should be in the range [0, 125].
```
> use exit code from recommended range

- design/2024-02-21-install-without-issuer.md
This design is to allow us to install csi-driver-spiffe before an issuer has been created. This allows us to install at the same time as cert-manager without having a strict dependency on cert-manager being installed (and configured) first.
This is for csi-driver-spiffe, but the intention is that something very similar should apply for istio-csr.
> Add design for runtime configuration of issuers

- .golangci.yaml
- internal/approver/controller/controller_test.go
- internal/approver/controller/test/suite.go
- internal/approver/evaluator/evaluator_test.go
- internal/approver/evaluator/extensions.go
- internal/approver/evaluator/extensions_test.go
- internal/csi/app/app.go
- internal/csi/driver/camanager_test.go
- internal/csi/driver/driver_test.go
- internal/csi/rootca/file.go
- internal/csi/rootca/file_test.go
- internal/flags/flags.go
- test/e2e/suite/carotation/carotation.go
- test/e2e/suite/fsgroup/fsgroup.go
Reduces the list of ignored linters by fixing the go code.
> Fix linters

- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
- internal/approver/evaluator/evaluator.go
1. Fixes a typo in a variable name
2. Adds the default container annotation which makes it easier to query logs for the csi-driver pod (similar to https://github.com/cert-manager/csi-driver/pull/223)
> Two minor tweaks

- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
Currently, if I want to view logs for a pod in the csi-driver-spiffe DaemonSet I type:
```console
kubectl logs -n cert-manager cert-manager-csi<TAB>
```
which will be automatically expanded to:
```console
kubectl logs -n cert-manager cert-manager-csi-driver-spiffe-
```
On a local single node cluster, I then have two options:
```console
kubectl logs -n cert-manager cert-manager-csi-driver-spiffe-<TAB>
cert-manager-csi-driver-spiffe-approver-66b4645b58-d8hrl  cert-manager-csi-driver-spiffe-ng927
```
If I want to view logs for the approver, I can type `a<TAB>` to get the approver logs, because there's a predictable suffix.
If I want to view the logs for the driver, I need to look up at the screen and look at what random character was used for the pod's name. In the example above, `n` but …
> Rename DaemonSet for easier tab completion

- internal/csi/driver/camanager_test.go
These timeouts are incredibly aggressive and caused test flakes on my machine when testing unrelated changes.
NB: I'm not 100% confident that these tests are really useful, but rather than ripping them out it seems easier to bump the timeouts
> Increase timeouts for camanager test

- internal/annotations/annotations.go
- internal/csi/app/app.go
- internal/csi/driver/driver.go
- internal/csi/driver/driver_test.go
This makes it simpler for us to test that annotations are correctly sanitized and ensures that all drivers - wherever they're created - will have sanitized annotations in the future.
Also makes some minor whitespace / comment adjustments and removes an unused `var err error`
> Move parsing of custom annotations to testable function

- deploy/charts/csi-driver-spiffe/templates/deployment.yaml
- internal/approver/app/app.go
- internal/approver/app/options/options.go
- internal/approver/controller/controller.go
- internal/approver/controller/test/suite.go
- test/e2e/suite/approval/approval.go
The approver currently filters CertificateRequest resources based on the issuerRef they have configured, which will be incredibly complicated to handle in a scenario where we allow runtime configuration of issuers.
It also doesn't really provide any guarantees, guardrails or value, but does introduce a race condition when the issuer is updated. Updating the issuer cannot be synchronized everywhere at the same time, so there's always a period after an issuer update in which the driver could be using the new issuer and the approver could be looking for the old issuer.
This commit removes the issuerRef for the approver while keeping backwards compatibility with existing uses of the `--issuer-*` flags.
It replaces filtering of CertificateRequests by issuerRef with filtering based on the …
> Remove issuerRef from approver

- make/test-e2e.mk
Simple change to help with development; tested locally that this has no effect unless a test name is given
> Add env var for focusing on individual e2e tests

- test/e2e/suite/carotation/carotation.go
- test/e2e/suite/fsgroup/fsgroup.go
- test/e2e/util/util.go
We have some repeated code in our e2e tests already, and I'm going to need similar functionality in e2e tests in an upcoming PR to add runtime configuration.
This PR abstracts that logic into a central location, making the tests less noisy in the process. This doesn't change any logic.
> Add e2e util package to abstract common e2e tasks

- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
- deploy/charts/csi-driver-spiffe/templates/deployment.yaml
- deploy/charts/csi-driver-spiffe/values.schema.json
- deploy/charts/csi-driver-spiffe/values.yaml
When i tried to deploy a helm chart to tainted nodes i figured out that templates didn't contain the Kubernetes scheduler fields like:
* tolerations
* nodeSelector
* affinity
* topologySpreadConstraints
Added it to deployment and daemonset.
> Added tolerations,nodeSelector,affinity,topologySpreadConstraints

- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
- deploy/charts/csi-driver-spiffe/templates/role.yaml
- deploy/charts/csi-driver-spiffe/templates/rolebinding.yaml
- deploy/charts/csi-driver-spiffe/values.schema.json
- deploy/charts/csi-driver-spiffe/values.yaml
- internal/csi/app/app.go
- internal/csi/app/options/options.go
- internal/csi/driver/driver.go
- make/test-e2e.mk
- test/e2e/framework/config/config.go
- test/e2e/suite/import.go
- test/e2e/suite/runtimeconfiguration/runtimeconfiguration.go
- test/e2e/util/util.go
Currently, installing csi-driver-spiffe requires that users have already installed cert-manager and already created an issuer, because issuer config must be passed in at startup.
This presents problems when users wish to install everything and configure it later. It also means that it's not possible to change issuers without risking downtime of the driver, which in turn implies downtime in being able to create any pod which relies on csi-driver-spiffe.
This PR adds support for runtime configuration through a ConfigMap. If enabled, the ConfigMap will be watched and if it exists and the configuration is value, the issuer specified in that ConfigMap will override any issuer configured at runtime.
To support the e2e tests for this, we also add lots of helper functions for generating issuers …
> Allow runtime configuration of issuers

- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/templates/clusterrole.yaml
- deploy/charts/csi-driver-spiffe/values.schema.json
- deploy/charts/csi-driver-spiffe/values.yaml
Implements the same logic as https://github.com/cert-manager/csi-driver/pull/272/commits in this CSI driver also
> feat: add RBAC for OpenShift SecurityContextConstraints

- make/00_mod.mk
The upstream images changed, thus we have to update the shas.
> Update busybox sha to match upstream

- make/00_mod.mk
E2e tests are failing currently because of this!
> Update busybox SHAs to match upstream

- make/00_mod.mk
The images were overwritten in the docker registry.
> Update busybox shas due to upstream change

- OWNERS
OWNERS_ALIASES is managed centrally in makefile-modules and will get updated automatically.
> Update OWNERS file to use OWNERS_ALIASES

- deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
This passes locally for me with no errors; this can be merged after the kubeconform tests are added via makefile-modules.
EDIT: This can now be merged, which should unblock #285
> Fix bad security context on DaemonSet

- deploy/charts/csi-driver-spiffe/README.md
- deploy/charts/csi-driver-spiffe/values.schema.json
- deploy/charts/csi-driver-spiffe/values.yaml
As per https://github.com/cert-manager/csi-driver-spiffe/blob/main/RELEASE.md#preparing-for-a-release
> BEFORE doing a release, check if the other images in the csi-driver Helm chart need to be updated.
> These are:
> registry.k8s.io/sig-storage/livenessprobe (.Values.livenessProbeImage.tag)
> registry.k8s.io/sig-storage/csi-node-driver-registrar (.Values.nodeDriverRegistrarImage.tag)
Artifacthub is showing the vulnerabilities in these two images:
* https://artifacthub.io/packages/helm/cert-manager/cert-manager-csi-driver-spiffe/0.9.1?modal=security-report
Links:
* https://github.com/kubernetes-csi/livenessprobe/releases/tag/v2.16.0
* https://github.com/kubernetes-csi/node-driver-registrar/releases/tag/v2.14.0
Slack thread: https://kubernetes.slack.com/archives/CDEQJ0Q8M/p1750949202461539
> Bump sidecar image versions in preparation for release
