deploy/charts/csi-driver-spiffe/templates/deployment.yaml
Passes the correct driver name.
Signed-off-by: irbekrm <irbekrm@gmail.com>
=> Corrects the driver name

README.md, SECURITY.md
=> Update links to cert-manager/cert-manager in SECURITY.md and README.md

Dockerfile.approver, Dockerfile.driver
=> Updates to go v1.18 in Dockerfiles

deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
=> Bumps bump-csi-node-driver-registrar to `v2.5.0`

deploy/charts/csi-driver-spiffe/templates/daemonset.yaml
=> Adds liveness probe to csi-driver

deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/templates/daemonset.yaml, deploy/charts/csi-driver-spiffe/values.yaml
Branched from https://github.com/cert-manager/csi-driver-spiffe/pull/8 which should be merged first.
/assign @munnerz
=> Configurable side cars

Makefile, deploy/charts/csi-driver-spiffe/Chart.yaml, deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/values.yaml, internal/csi/driver/driver.go
/assign @munnerz 
/hold
Until we are ready to release
=> Updates app version to v0.2.0

deploy/charts/csi-driver-spiffe/Chart.yaml, deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/templates/daemonset.yaml, deploy/charts/csi-driver-spiffe/templates/serviceaccount.yaml, deploy/charts/csi-driver-spiffe/values.yaml
Signed-off-by: Sitaram IYER <sitaramkm@gmail.com>
Add support for including imagePullSecret in Helm for csi-driver-spiffe to pull images from private repo. Fixes #17
=> Support for including imagePullSecrets in Helm

deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/templates/daemonset.yaml, deploy/charts/csi-driver-spiffe/templates/deployment.yaml, deploy/charts/csi-driver-spiffe/values.yaml
=> Adds priorityClassName option to helm chart

OWNERS, README.md
- Applies changes in https://github.com/cert-manager/website/pull/1171 to README
- center-aligns beginning of README
- Updates OWNERS
=> README and example updates

Makefile
Various helm-related quality-of-life fixes
=> Bump helm version, improve install, add chart target

deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/templates/daemonset.yaml, deploy/charts/csi-driver-spiffe/values.yaml, internal/approver/controller/controller.go, internal/csi/app/app.go, internal/csi/app/options/options.go, internal/csi/driver/driver.go
https://github.com/cert-manager/csi-driver-spiffe/issues/59
=> Add certificate requests annotations flag

make/00_mod.mk, test/e2e/suite/carotation/carotation.go, test/e2e/suite/fsgroup/fsgroup.go
Fix version to "1.36.1-musl". I'm using the musl version because it is much smaller.
=> Use fixed version for busybox image

OWNERS
I am already a reviewer of the cert-manager repo, this is to add same permissions here
=> chore: add thatsmrtalbot as reviewer

deploy/charts/csi-driver-spiffe/Chart.yaml, deploy/charts/csi-driver-spiffe/README.md
Should greatly improve the visual appearance of the artifacthub page.
=> Update Chart.yaml properties

deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/values.yaml, make/00_mod.mk
Switch to https://github.com/cert-manager/helm-tool to perform doc generation.
=> Use helm-tool to generate Helm README.md

.github/workflows/release.yaml, make/02_mod.mk
The release target was missing the build & publish step for the approver image.
=> Fix release target and add approver image

deploy/charts/csi-driver-spiffe/templates/clusterrole.yaml, deploy/charts/csi-driver-spiffe/templates/clusterrolebinding.yaml, deploy/charts/csi-driver-spiffe/templates/csidriver.yaml, deploy/charts/csi-driver-spiffe/templates/daemonset.yaml, deploy/charts/csi-driver-spiffe/templates/deployment.yaml, deploy/charts/csi-driver-spiffe/templates/metrics-service.yaml, deploy/charts/csi-driver-spiffe/templates/metrics-servicemonitor.yaml, deploy/charts/csi-driver-spiffe/templates/role.yaml, deploy/charts/csi-driver-spiffe/templates/rolebinding.yaml, deploy/charts/csi-driver-spiffe/templates/serviceaccount.yaml
similar to https://github.com/cert-manager/approver-policy/pull/381
=> Use same include statement for labels everywhere & add labels to pod templates

deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/templates/_helpers.tpl, deploy/charts/csi-driver-spiffe/values.schema.json, deploy/charts/csi-driver-spiffe/values.yaml
Add Helm option to add common labels to all installed resources.
=> Helm Add commonLabels option

make/00_mod.mk
=> Update digests of upstream busybox docker image

.golangci.yaml, internal/csi/rootca/file_test.go, test/e2e/suite/carotation/carotation.go, test/e2e/suite/fsgroup/fsgroup.go
Checked all found issues and applied fixes/ #nosec statements.
Now that all issues are fixed, I removed the gosec linter from the ignored section so future issues will be detected.
=> Fix gosec issues and enable gosec linter

make/test-e2e.mk
Uses cmctl to approve the e2e test certificate, since the previous logic causes problems if other CRs are present in the e2e cluster and found by the `kubectl get`
Plus cmctl is cleaner to use for this anyway!
=> Change approval of e2e issuer to use cmctl

deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/values.schema.json, deploy/charts/csi-driver-spiffe/values.yaml
Signed-off-by: Adam Talbot <adam.talbot@venafi.com>
=> chore: update csi-node-driver-registrar

make/00_mod.mk
=> Fix digests for busybox images

RELEASE.md, deploy/charts/csi-driver-spiffe/README.md, deploy/charts/csi-driver-spiffe/values.schema.json, deploy/charts/csi-driver-spiffe/values.yaml
Similar to https://github.com/cert-manager/csi-driver/pull/357
=> Update other images, add release note section

internal/csi/driver/driver.go
=> Only watch for runtime configuration if provided
